### ISSUE TITLE
grasa-folk entry spelled grasa-fo1k

### ISSUE THREAD

**Issue by IG-Charlemagne** [stscoundrel/cleasby-vigfusson-next#544]
https://cleasby-vigfusson-dictionary.vercel.app/word/grasa-fo1k

I had no idea how else to let you know.

**Comment by stscoundrel** [comment]
Thanks! That seems to be typo in the original source, which can be found [here](https://github.com/stscoundrel/cleasby-vigfusson-dictionary). I'll try to fix that sometime soonish, maybe next week.

**Comment by IG-Charlemagne** [comment]
I appreciate your work!  Just glad I could help in a (very) small way. :)

**Comment by stscoundrel** [comment]
This has now been fixed in the latest release:

https://cleasby-vigfusson-dictionary.vercel.app/word/grasa-folk

Thanks for bringing this up, @IG-Charlemagne !
